### ISSUE TITLE
NerveNetwork Airdrop

### ISSUE THREAD

**Issue by nerve-admin** [NerveNetwork/nerve#1]
A Tribute to All Developers
 Get NVT Now
 
For All Developers Who Have Contributed Code to blockchain-related Projects
---------------->
  1. Follow @nerve_network on Twitter and join Nerve Discord（https://discord.gg/aDaxwJR）

 2. Add Nerve Github repository to favorites and submit your NULS wallet address to Issues, you will receive 200NVT!       
               
Here is Github link : https://github.com/NerveNetwork/nerve/issues
Note: **Only members who have contributed code to the blockchain project will be airdropped.**
![image](https://user-images.githubusercontent.com/56823576/79209242-b6b7e580-7e75-11ea-8e6e-4d76fcf8417c.png)

**Comment by rbohappy** [comment]
Hi，My NULS wallet: NULSd6HgVfveU6Bquy29yFESncpTPd3PKMAE2
Thanks！

**Comment by Berzeck** [comment]
This is an example on how to apply (after joining social media outlets)

Twitter: @Berzeck5
Discord: Berzeck#5584
Wallet Address: NULSd6HgbWr6CqPeH6Bi2BusgpNpfhVxqTWUY

**Comment by co1ote** [comment]
Hi, Iam a brazilian CS Bachelor and appreciate very much NerveNetwork project. I believe it can change crypto world. I dont have twitter but joined discord group.

Discord: co1ote#2309
Wallet Address:  NULSd6HgeGQAdbziuBtg9taiBWKpgA736Eo5U

You can count on me for any help.

**Comment by Filtreks** [comment]
Twitter: @SimaoVaz1904
Discord: Simão#3266
Wallet Address: NULSd6HgjFKcFsTuKhENDwhmSYp1xNxo4UTtP

**Comment by bookamp** [comment]
Discord: bookamp#3349
Wallet Address: NULSd6HgbSNYaMwwTk3D66EHkCSAwCSzWgqrn

**Comment by Andikaiqbalm** [comment]
Twitter @Andikaiqbalm2
Discord : Dikaiqbalm#3995
Nuls wallet : NULSd6HgbyApV2CBNLQG9tuYxbgXaeTAwtn2V

**Comment by corgian1** [comment]
> 1. aDaxwJR）
Great project!
Twitter: @ledacan2
Discord: corgian#2148
Wallet Address: NULSd6HgZsKgQemCEzLbVD7P248xuunHy1L3c

**Comment by iyan03** [comment]
Discord : yudia3335#0148
Twitter : @LilySOH6
Adress : NULSd6Hgf9tEuuotbmSrrBB63CZpAqe86XPyu

good project

**Comment by ginzitsu** [comment]
Discord id : ginzitsu#0506
Twitter id : @Owginn
Wallet Address : NULSd6HgZ5hNSvWgHmwsCm8SHca9DxA9cMFoW

**Comment by edison1204** [comment]
Discord id: edison1204#1569
Twitter id: @EDL_slkc
Wallet address: NULSd6HgcjgZxW38WzsZW4mhvWB4u1edcGXCD

**Comment by zoowii** [comment]
Discord id: zoowii#5216
Twitter id: @zoowii92
Wallet Address: NULSd6HgcTU2RgnPuNuYxDDUPRztMFBoHiaxF

**Comment by Izullubiez** [comment]
Twitter : @DzulkifliLubis1
Discord: Izullubiez#4155
Wallet : NULSd6HgiebbZCA37bFvb9tx8F2sFHfyPxtJA

**Comment by sunuwardono** [comment]
Twitter : @bunbalung 
Discord : eXchange™®#1675
NULS address : 
NULSd6HgWPGPKtTtch9Rw4KVxmCGJHiadRQx3

**Comment by jagokw1445** [comment]
Twitter : @Restana9
Discord : jagokw#3094
NULS Wallet : NULSd6HgZBwcuJbMgPtX6n3nfE8eq8wxpKFRX

**Comment by steffanomcrey** [comment]
Twitter : @parkdepi
Discord: Nandar #9284
Nuls Adress: NULSd6HghtnirkAJAqPtQqcoTt9NszPq8Gdwm

**Comment by lvthrn** [comment]
twitter : @wcekb
discord : proximity#3623
nuls address : NULSd6HgaHDXR5Zt4HnaZj7Wae4tLjSUk4FhN

**Comment by alhilmi01** [comment]
twitter: @alhilmi0
discord: Ahmad Habib Al Hilmi#5573
nuls address: 
NULSd6Hgac7PT6eWcJf7B7Je4NbizyBHu3oj8

**Comment by luckypickle** [comment]
Twitter : @sunny_love_it
Discord: sunnypickle#7226
Wallet : NULSd6HgiKNbzEEMve2GwYMqZDLiCFYq2zUa2

**Comment by hendrair** [comment]
Twitter: @hendrai79588782
Discord: bhendot#4733
Wallet: NULSd6HgYokCHLRGaFHUF8VC9L7TQPFXvHAs5

**Comment by japanindo** [comment]
Twitter: @CryptIdol
Discord: blogoesman#4320
Wallet: NULSd6HgdtLrxY8dXGdhciC6gwnytvkq4UExa

**Comment by CQBeer** [comment]
Discord: Pen#1548
Wallet Address: NULSd6HgVEuAVYrRZjWWZhmhNvUUtoZohE74J

**Comment by tyak28** [comment]
Twitter: @oksarina_tia
Discord: Tia Oksarina#3382
Nuls Address: NULSd6HgfubDmLnuKfrgD7qBpmN1bBxeKQpzw

**Comment by lichao23** [comment]
Twitter: @lichao23
Discord: lichao#4407
Wallet Address: NULSd6Hghso8XR5H8c1fPuPhjCN5q4rEwHSza

**Comment by ameliasunjaya1** [comment]
twitter: @ameliasunjaya00
discord: Amelia Sunjaya#3808
nuls addres: NULSd6HgYZ3RA6P23CHNWVZoF7etoZfmypPkp

**Comment by jarpani12** [comment]
twitter: @juli_arpani
discord: Juli Arpani#3326
nuls addres: NULSd6HgXf9q9pgGqqWA6cBu9sTW8i59Ax2YZ

**Comment by saleopers** [comment]
Twitter: @syafiii23
Discord: @syafiii
Wallet address:
NULSd6HgWkPRz7yrcGq7oGQZDX9KiM1xVLsLS

**Comment by waveTan** [comment]
> A Tribute to All Developers
> Get NVT Now
> 
> For All Developers Who Have Contributed Code to blockchain-related Projects
> ---------------->
> 
> 1. Follow @nerve_network on Twitter and join Nerve Discord（[https://discord.gg/aDaxwJR）](https://discord.gg/aDaxwJR%EF%BC%89)
> 2. Add Nerve Github repository to favorites and submit your NULS wallet address to Issues, you will receive 200NVT!
>    Here is Github link : https://github.com/NerveNetwork/nerve/issues

NULSd6HgVv7fFsTS711EpHX7pcWdXpHEtCara

**Comment by Ardianto99** [comment]
Twitter : @ArdiantoGMB
Discord: ArdiantoGMBL#6249
Wallet Address:
NULSd6HgaVvmRaerAx1y6T2y14mmXzS7Y8a5j

**Comment by Taron0777** [comment]
Twitter : @Haykh7707
Discord: hke99 | HeliosProtocol.io#8562
Wallet Address: NULSd6HgZbMyUc9AcSw6SNSwnSZVhxqcA9Re1

**Comment by Taron0777** [comment]
Twitter : @Haykh7707
Discord: hke99 | HeliosProtocol.io#8562
Wallet Address: NULSd6HgZbMyUc9AcSw6SNSwnSZVhxqcA9Re1

**Comment by CNazar** [comment]
Twitter:@Natan53404237
Discord: pred#6145
Wallet Address: NULSd6HgbuCBzRJzLu2Vt2LgExG3WY1Gq4Q5s

**Comment by zain0l** [comment]
Twitter: @aryoguatama
Discord: @zain5988
Wallet address:
NULSd6HgeCtcjTtv4BFFk8nQzpHZ1vBuj4cH7

**Comment by jby0539** [comment]
Twitter: @shanzhaibi
Discord: jby0539#6144
Wallet Address: Twitter: @Berzeck5
Discord: Berzeck#5584
Wallet Address: NULSd6HgbWr6CqPeH6Bi2BusgpNpfhVxqTWUY

**Comment by Rdharief** [comment]
Twitter : @Cucusultan12
Discord : Rdharief#8958
Wallet Address : NULSd6HgbYec67JfFNzvfgQLKLD4uFMjzfEZm

**Comment by zimone91** [comment]
Twitter : @zimone91
Discord : Zim_onE#0869
Wallet Address : NULSd6HgVadJoBXy8uS36zS1q6GwYeWqPJSRv

**Comment by webber1927** [comment]
Twitter: @DenadaRein
Discord: twochiken#5826
Wallet Addres: NULSd6HgXJdVS7PLcv21udPNnrfDo94PmT87C

**Comment by prabowokentod** [comment]
Twitter: @Siskaeeee4
Discord: prabowokentod#1696
Wallet Addres: NULSd6HgjDC3JZXTihii2Djwg8peMwz7H7N3y

**Comment by AriesMeiP** [comment]
Twitter: @MeiPriyana
Discord: anam#5872
Wallet address:
NULSd6HgfPFmTE1TsLE6r4vK6MKfJqeffrnU1

**Comment by tag0313** [comment]
Twitter: @tag0313
Discord: tag0313#2067
Wallet Address: NULSd6HghJdWFpNHQMZZF5mtj4K3TAsPEsTLw

**Comment by tag0313** [comment]
Twitter: @tag0313
Discord: tag0313#2067
Wallet Address: NULSd6HghJdWFpNHQMZZF5mtj4K3TAsPEsTLw

**Comment by niels1286** [comment]
Tiwitter:@Niels1286
Discord:Niels-NULS#5904
Wallet Address:NULSd6HgZkPDuWG7vZP8yQiLwMSxEFzY1rUNr

**Comment by lijunzhou** [comment]
Discord:zhoulijun#7463
Wallet Address:NULSd6HgewU4xL3B8r25j1t9E8S3eMBjwCcfb

**Comment by zhouwei1985** [comment]
Discord:zhouvivi#1972
Wallet Address:NULSd6HghBbmWz3zswFNHfPQpD1zH8NxXasZ1

**Comment by yeealbert** [comment]
Tiwitter:@yzhonglin
Discord:Albert#1962
Wallet Address: NULSd6HggJxUYdbwCSiRmSqXegQGH1ioYhU5H

**Comment by MIMIEYES** [comment]
Tiwitter:@PierreLuohao
Discord:PierreLuo#1810
Wallet Address: NULSd6HghVxPuCQ8cm6xX8r814UXJWRi4887k

**Comment by vipcaolan** [comment]
Twitter: @HoangNghiep12
Discord: HoangNghiep#2332
Wallet Address: NULSd6HgW3N8cDCPTgbH82Aw8Yd2yej4TbxeN

**Comment by vietrap94** [comment]
Twitter: @BlackTiger1203
Discord: vietrap94#7891
Wallet Address: NULSd6HgbhkuP7reDH9jxtrh2B8VG9HF6ELBY

**Comment by bocmndoi2018** [comment]
Twitter: @ngocngan1902
Discord: Bố Đời#2008
Wallet Address: NULSd6HgcHtWxjcqKKYSgHNfv57SvU6nLTEbt

**Comment by hbaonam218** [comment]
Twitter @CaoLanVip
Discord : Hbaonam#7027
Nuls wallet : NULSd6Hgc9QbzrsEHua6o5hi4ULfHkEuuLPnj

**Comment by thichsex1203** [comment]
Twitter: @Tet2511
Discord: Thich Choi#4313
Wallet Address: NULSd6HgbeJXtRtRCNehu1rtx4PonFsX3gQ7S

**Comment by huangsheng912** [comment]
Discord: huangsheng#3458
Wallet Address: NULSd6HgZv4u7GErcpxF3DydegBYumW5vamvs

**Comment by tiarmando12** [comment]
discord: Tito Armando#7137
twitter: @titoarmando02
Nuls Address: 
NULSd6HgfcKmnwdgSiCgYg6RoxXK3q8rM9ADJ

**Comment by nuocmamcuatung** [comment]
discord: nuocmam#6901
twitter: @ninzcute14
Nuls Address:
NULSd6HgbYeJz2QpVB8sq8CuPRZ1FAEnfiUQh

**Comment by phutranctvl** [comment]
Twitter: @ChieuHoang2
Discord: nuocmam#7605
Wallet Address: NULSd6HgbXkppW3F8axJwv2get4ZNzQBcf355

**Comment by ksmhmzah** [comment]
Twitter: @hamzah_kemas
Discord: Kemas Hamzah#0207
Nuls Address: NULSd6HgU8i9JR7o2gEL6gDqetdB6AVWVmj8a

**Comment by trandinh98** [comment]
Twitter: @phamvan89037676
Discord: DONGPHUOC#5331
Wallet Address: NULSd6HgZZwaTYg8SLuLTrN529U36Uk2fNpHw

**Comment by so7choem** [comment]
>     1. @nerve_network
Twitter: @HoangLa61338890
Discord: nuocmam#3787
Nuls Address: NULSd6HghqjNGhfXLLggC5ZKrejPDPDhVp9zo

**Comment by jimmy90324845** [comment]
Twitter: @jimmy90324845
Discord: aalonfg211d#1142
Wallet Address: NULSd6HgjT2JZ1k2rBhhkYoCPkJYBYxiqhpAy

**Comment by absbro64** [comment]
Twitter: @Nghiep1203
Discord: Bao Nhi#2174
Wallet Address: NULSd6HgdqYXVpNiaAo6tfG5mBxk8QTVUrK1i

**Comment by sutugia91** [comment]
Twitter: @elguapovilo
Discord: sutugia91#9840
Wallet Address: NULSd6HgWaaDDkhozjuv8H4ejrargtnC3jNC5

**Comment by mlthanh839** [comment]
Twitter: @VaiNhai
Discord: Thanh ML#8280
Wallet Address: NULSd6HgiqKGbQm6bynhuyj4dALUKpjLzjsKs

**Comment by codonkt0022** [comment]
Twitter: @nhayhetco
Discord: Nhay Lam#3276
Wallet Address: NULSd6HgZUr6xThBphjvqjaxrepxy4DbK39nD

**Comment by hvnghiep** [comment]
Twitter: @BaoNam2020
Discord: H Nam#3332
Wallet Address: NULSd6HggHQsai2U8cfn3Dzn64kURy4SuszaD

**Comment by setoadi** [comment]
Twitter: @setoay1
Discord: setoadi#0506
Wallet Address: 
NULSd6HgYB5iTYLdHHdLaaaxrhyBcqBWBz5kL

**Comment by ngakooog** [comment]
Twitter: @truongthon14
Discord: Bao Nhi#7714
Wallet Address: NULSd6Hgco79nQUxYcCFcxBqaFnWuaawVrmB3

**Comment by omnnbhaa** [comment]
Twitter : @nghieptrominfo
Discord: omnnbhaa#5473
Wallet Address: NULSd6HgVrTd2rX99D92rhfC2HqGb2d1MZqS7

**Comment by giangtrachdoon** [comment]
Twitter: @60giaybd
Discord: giangtrachdoon#9986
Wallet Address: NULSd6HgUKyoTCAihi5W81aSUryrugUw4jmxd

**Comment by qammnna** [comment]
thanks
Twitter @cryptodicor
Discord : qammnna#5792
Nuls wallet : NULSd6HgU3mFxd4S2ES3R9ypW4EesCHVUKSFK

**Comment by hiangyei** [comment]
Twitter: @ovuong2
Discord: hiangyei#3973
Wallet Address: NULSd6HgbMrJBDpsPDF9TnyBP2Zh5sP4Ts7Wj

**Comment by langtungtom** [comment]
Twitter : @cointopfre
Discord : langtungtom#2704
Nuls wallet : NULSd6HgXCWyz378Qvf8whzns9iLamuQkEpvj

**Comment by syafrudin19971** [comment]
twitter: @syafrudin777
Discord: syafrudin#9397
Nuls Address: NULSd6Hgaf3SMe2PmQkLCR5y6Stweh6BC8VBZ

**Comment by msyafris** [comment]
twitter: @msyafrisaputra
Discord: Syafri Saputra#2013
Nuls Address: NULSd6Hge1PibgJFeDkiA6Z7iwmuUZNvsZQvA

**Comment by khai261291** [comment]
twitter: @sungkikhai
Discord: khai261291#6784
Nuls Address: NULSd6HgVPXG9uxwGUVuGUGG2KBmbkjL5FYQT

**Comment by khang23062018** [comment]
twitter: @kutaka8
Discord: khang23062018#0785
Nuls Address: NULSd6Hga9pkY4UangYns1FbDki3XTvJso2cc

**Comment by k0ystupld** [comment]
Twitter: @phatloc8888
Discord: 512mieww#4714
Wallet Address: NULSd6HgbazKGFDjY6GkNwe5Lmg8fftgydnRz

**Comment by kakimura34567** [comment]
Twitter: @xinhkaki
Discord: kakimura34567#5831
Wallet Address: NULSd6HgU7GtGu4EFcTRNxdzHtwR3RJRbe5NY

**Comment by 512miewww1** [comment]
Twitter: @Thaomy99389404
Discord: ging12#2511
Wallet Address: NULSd6HgcLbHvkkeZhpRvaYHAW2YHipX4nSoG

**Comment by kimasaki444** [comment]
Twitter: @bukikhy
Discord: kimasaki444#2116
Wallet Address: NULSd6Hgh7hieHQoLbyVdoMhWtaFj3VkM8VZZ

**Comment by akiramaki4567** [comment]
Twitter: @nikikhi1
Discord: akiramaki4567#5487
Wallet Address: NULSd6HgUNesehn75kHwFxzjkBsGBw2eGCJro

**Comment by akusaka476** [comment]
Twitter: @dcvgil
Discord: akusaka476#1970
Wallet Address: NULSd6HgY5VMqereLWSD14EmcDBR99Wkv1515

**Comment by kalakaka04** [comment]
Twitter: @kalakaka04

Discord: kalakaka04#2476
Wallet Address: NULSd6HgZXYRyL7FHh9ZjYYHEU6tkJd2oUKB9

**Comment by mrxoan1991** [comment]
Twitter: @mmilasi76
Discord: quangkhai#3420
Wallet Address: NULSd6HgeRiim5NHzhJJfDCfcVgZR34spKMki

**Comment by ronomata24** [comment]
Discord id: mrxoan#3765
Twitter id: @Xunhok1
Wallet address: NULSd6HgUMe9m44uKawAAF6nhUJKmKzDuS4wV

**Comment by mumalilika465** [comment]
Discord id: mumalilika465#5105
Twitter id: @sakjhgf1

Wallet address: NULSd6HggMKfwzcmuJDEvnXSC4yZZpjtNFecK

**Comment by anggola476** [comment]
Twitter: @dakikhf
Discord: anggola476#0720
Wallet Address: NULSd6HgdSd2UFnmEN7ckupAyYp2L4662ZiCM

**Comment by MrXoan** [comment]
Twitter : @icuiuicui77
Discord : baptran#5148
NULS Wallet : NULSd6HgZAd8yrnyka7PAvE8kYuhVZoMRMayQ

**Comment by tamimika456** [comment]
Twitter : @sakami43
Discord : tamimika456#0391
NULS Wallet : NULSd6HghBVZfkhKTVJX5pfAiVZgrCQWWajxp

**Comment by saccumuti45** [comment]
Twitter : @minhlaai2
Discord : saccumuti45#3995
NULS Wallet : NULSd6HgVKAQSR6wt9LcQn9qMCtCp6oMHU5Du

**Comment by sakahuong21** [comment]
Twitter : @sakig18
Discord : sakahuong21#2683
NULS Wallet : NULSd6HgdeDJXwTLiEpPaNztZgeevH7GunLgr

**Comment by nguyenkhai8691** [comment]
Twitter : @doilathethoi821
Discord : nguyenkhai8691#9225
NULS Wallet : NULSd6HgavRegKuQqAsAZnSg8yDmZFtr5z5bH

**Comment by dunggeon1111** [comment]
Twitter : @samgms4
Discord : dunggeon1111#1583
NULS Wallet : NULSd6Hga5xT6MV7N5QKz6QAmcR4vzEbV1cmv

**Comment by colonhue11** [comment]
Twitter: @Lih91301006
Discord: longphi09#9617
Wallet Address: NULSd6HgV3oB2wcb7VDuHSy7ZZZtWHdYBu1Cf

**Comment by Piter115** [comment]
Twitter : @NguyenTuMinh555
Discord: tatvuong1#6197
Wallet : NULSd6Hghy6AKyBbELrgMvcoYY7VzvSYohJug

**Comment by mmocuatung** [comment]
Twitter: @tieuxanh1
Discord: khoaito#8106
Wallet Address: NULSd6HgZWo5MsVQ8yWz15icco6Cdgj6Sod2g

**Comment by cuatungico** [comment]
> 
> 
> A Tribute to All Developers
> Get NVT Now
> 
> For All Developers Who Have Contributed Code to blockchain-related Projects
> ---------------->
> 
>     1. Follow @nerve_network on Twitter and join Nerve Discord（[https://discord.gg/aDaxwJR）](https://discord.gg/aDaxwJR%EF%BC%89)
> 
>     2. Add Nerve Github repository to favorites and submit your NULS wallet address to Issues, you will receive 200NVT!
> 
> 
> Here is Github link : https://github.com/NerveNetwork/nerve/issues
> Note: **Only members who have contributed code to the blockchain project will be airdropped.**
> ![image](https://user-images.githubusercontent.com/56823576/79209242-b6b7e580-7e75-11ea-8e6e-4d76fcf8417c.png)

Twitter: @NguyenH06588397
Discord: cuatungico#9338
Wallet Address: NULSd6HgW7oG6QF9iF8uCADpUPgwss64KPpPG

**Comment by cuatungico** [comment]
Twitter: @NguyenH06588397
Discord: cuatungico#9338
Wallet Address: NULSd6HgW7oG6QF9iF8uCADpUPgwss64KPpPG

**Comment by cuatungico** [comment]
Twitter: @aprilmiralles18
Discord: cuatungtrongtoi#8390
Wallet Address: NULSd6HgU6nTspqraYgU79GyGkKdjUTLzN4hT

**Comment by ngtrongtoi** [comment]
Twitter: @aprilmiralles18
Discord: cuatungtrongtoi#8390
Wallet Address: NULSd6HgU6nTspqraYgU79GyGkKdjUTLzN4hT

**Comment by gcmoosj** [comment]
Discord : gcmoosj#9422
Twitter : @Ryham24917505
Adress : NULSd6Hga87yKm2Y5QJojWScfFtqfu6BoYLSx

good project

**Comment by hanbpha** [comment]
Twitter: @htv9kick
Discord: hanbpha#4209
Wallet Address: NULSd6HgjbCWQMtNfpd7Q5ufyVYqGThJtf5pL

**Comment by buinhathung97154** [comment]
Twitter: @ngocthibichdo1
Discord: buinhathung97154#3119
Wallet Address: NULSd6HgVV6LBK6vwPkb3EYwttbGTAcuUmccp

**Comment by shinchainindia** [comment]
Twitter @maulian12
Discord : shinchainindia#4371
Nuls wallet : NULSd6HgisNUvDW1RG2CbzhG2brdutMaXon6f

**Comment by chauhieudung61108** [comment]
Twitter: @Linkon58061792
Discord: chauhieudung61108#7115
Wallet Address: NULSd6HgWCzaA3mRH4HtcpLBtf4U9ZekxByjC

**Comment by chuduyhieu** [comment]
Twitter : @Sanho61838690
Discord : chuduyhieu#1087
Nuls wallet : NULSd6HgfovwEbK41N8eMtBEZadpePzLrSoki

**Comment by steventuong** [comment]
> Hi, Iam a brazilian CS Bachelor and appreciate very much NerveNetwork project. I believe it can change crypto world. I dont have twitter but joined discord group.
> 
> Discord: co1ote#2309
> Wallet Address: NULSd6HgeGQAdbziuBtg9taiBWKpgA736Eo5U
> 
> You can count on me for any help.

Hi, this promotion is initially for blockchain devs only. Can you state which blockchain projects you have contributed to? There may be promotions for the broader development community at a later stage. Thanks.

**Comment by youwenbusi** [comment]
Discord：AFEE#8621
Twitter：@AFEE90900803
Nuls wallet：NULSd6HgXLkuDAu9oKGPfWL5YjNMvQnzReLCq

**Comment by anislonthe** [comment]
Twitter: @GunawanCloud
Discord: paijigancok8979
Nuls Wallet: NULSd6Hgb5a3pYsDJrhafMNdKxB2gzH2iwAxo

**Comment by wetezos** [comment]
Twitter:@jun22408941
Discord:Huang#9950
Nuls Walllet:NULSd6HgcrLegYGhrJwux3GfeZJJKM1qFidnM

**Comment by hanzuri** [comment]
Twitter:@Xoantran2
Discord:tranrung#9843
Nuls Walllet: NULSd6HgWovw7iVgLomi8JCrLAFQLbECdMdsE

**Comment by Berzeck** [comment]
Only 7 people met the criteria, remember that you needed to  follow our twitter and join discord too
The winners are:
zoowii 
steffanomcrey
alhilmi01
CNazar
jby0539
youwenbusi
wetezos

for the winners please confirm that you hold the private keys of the NULS address you sent (exchange addresses fro example won't work)

**Comment by Berzeck** [comment]
bookamp
luckypickle
CQBeer
lichao23
waveTan
Taron0777
tag0313
niels1286
lijunzhou
zhouwei1985
yeealbert
MIMIEYES
huangsheng912

Please follow twitter and/or join discord to receive your reward

**Comment by shevardhani** [comment]
Twitter: @kun_crypto
Discord: MrDhani#8409
Nuls Wallet: NULSd6HgWBAgMYrHVn76BJ9SwajtvxLXWLtnE

**Comment by gejinxiaonuan** [comment]
Twitter: Qiuqiusss
Discord: qiuqiusss#4770
Nuls Walllet: NULSd6HgZ1adrv7XN6jV1N5WjSjNAXyoB7KnS

**Comment by nerve-admin** [comment]
![image](https://user-images.githubusercontent.com/56823576/85124300-43a76280-b25c-11ea-8c0e-de75b6201b3e.png)
Assets have been issued

**Comment by CNazar** [comment]
THX!!!!!!

19 червня 2020, 13:40:52, від nerve-admin <notifications@github.com>:




Assets have been issued

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.



--
NAZAR

**Comment by Ardianto99** [comment]
Not recieved

Pada tanggal Jum, 19 Jun 2020 17.50, CNazar <notifications@github.com>
menulis:
